### PR TITLE
Create it.yml

### PR DESCRIPTION
**Pull request by PeopleInside**
Add file for the Italian support. https://github.com/FriendsOfFlarum/links/issues/12

### CODE REVIEW

**Comment by datitisev** [comment]
Thanks for the PR to our extension. Sadly, we won't be merging it as we've decided to only maintain English locale and leave other languages to language packs (you can read more about why [here](https://discuss.flarum.org/d/19971-extensions-translation-in-their-own-repository-or-in-language-pack)).

This applies to all the PRs you've made to Friends of Flarum extensions. Feel free to PR to am Italian language pack with these translations, but I'll be closing this PR.

Thank you!

**Comment by PeopleInside** [comment]
This decision is just for your extension or will be to all Flarum extension?
I cannot imagine a Flarum community that not support other languages or just not support extension to be in other languages. How I can have a community in a language different from English if i need have all extension to be showed to the visitor in a different language?

I cannot understand. Will see what the future of Flarum will be.

**Comment by datitisev** [comment]
@PeopleInside It's for all FriendsOfFlarum extensions. Not having to maintain other locales makes it easier to update and maintain the extension itself, leaving the translating to others.

See https://discuss.flarum.org/d/19971-extensions-translation-in-their-own-repository-or-in-language-pack for a discussion on the pros and cons of this approach, and why we've decided to go with it.

**Comment by PeopleInside** [comment]
So i suppose in the future an user interested into translate for his community the extension will be no more able to do this. Now seems easy just create the file, in the future will be no more possible or extremely complicated? I added to discussion on Flarum post, will see to understand better.

I hope this decision will not create more issue to me when something is not working... in this case just fix with a language file: very easy, in the future i have no clear how will be. Thanks.

**Comment by datitisev** [comment]
@PeopleInside This approach should not make things harder, the point is to simplify the process. Extension developers maintain the extensions while language pack developers maintain their translations, without overlap (excluding English locale).

After reading your post, I feel like I need to clarify something, so I apologize if I didn't communicate the point properly. 

Friends of Flarum extensions can still be translated, it's just that we won't support these translations ourselves as it creates more work and pressure. We want language packs to translate our extensions, after all, that is their purpose. We just don't want to have to do it ourselves.

In the past, other locales would usually end up outdated anyway, so they didn't serve much purpose.

**Comment by PeopleInside** [comment]
Thanks for the clarification.
I still need to understand how will work in the future.

Links extension doesn't support Italian and this create issue on my community that i solved in just some minutes by creating the Italian file and just upload into the right folder.

In the future if an extension like this is not supporting Italian an user as me will be able to understand how fix and simply how translate or just will be forced to ask support and wait for the support in the future?

**Comment by datitisev** [comment]
Instead of putting the Italian translation in the extension's `locale` folder, you'll add it to an Italian language pack's `locale` folder instead (with a different name, like `fof-links.yml`).

So the process should still be simple, you'll just be putting the files in a different folder.

Hope that helps 🙂.

**Comment by PeopleInside** [comment]
Thanks, will see how will be :)

**Pull request closed without merging**
