### PR TITLE
Active links

### PR DESCRIPTION
**Pull request by clarkwinkelmann**
Add a special class and styling to active internal links.

Also allows for further customization in custom CSS.

Two notes on the extension:

I noticed that the `.editorconfig` defines indentation as 2 spaces, yet the JS is indented with 4 spaces. So I had to skip auto-formatting my code.

Also I noticed the dist file is not compiled with `build`, but with `dev`. Might be worth it to enforce having only the `build` version commited ?

### CODE REVIEW

**Comment by clarkwinkelmann** [comment]
Also woop because of this I messed up the indentation in my `less` file. Let me know if you prefer 2 or 4 space indent before I fix this :smile:

**Comment by Ralkage** [comment]
@datitisev your call on this :)

**Comment by datitisev** [comment]
@clarkwinkelmann Thanks for the PR. Use the `lint` script to lint/format the JS with prettier, and don't worry about the LESS file indentation.

**Comment by clarkwinkelmann** [comment]
@datitisev I ran the lint, it left the files as it, so I guess it's all right.

You might still want to update that editorconfig though :thinking:

**Comment by datitisev** [comment]
@clarkwinkelmann Feel free to update the editorconfig yourself. 

About the dist files, are you compiling them for development or production? They don't look uglified, so that's why I'm asking. `npm run build` for prod. (This is not a requirement, but will make the file size smaller for the users so we should probably do it, at least when someone remembers lol)

**Comment by clarkwinkelmann** [comment]
@datitisev done !

I previously didn't run the build command because it was already not run in master and I didn't want to create a bigger diff than necessary. But now if you merge, master will have my minified files :)

I hope no other change to the javascript was merged to master since I branched out, but I guess not because GitHub doesn't report any conflict.

And I updated for editorconfig to ease the pain of future contributors :hear_no_evil:

**Comment by datitisev** [comment]
Thanks!

**Pull request merged**
